### ISSUE TITLE
Example of command line parameters

### ISSUE THREAD

**Issue by mkgn** [gregl83/mknft#2]
I have got it to build properly using rust. However i think I am doing something wrong when giving parameters.

I have your config.json and mknft.psd in D:\Projects\Rust\mknft\target\debug\examples directory which I use for **SRC** 
For **DEST** I have created a folder in D:\Projects\Rust\mknft\target\debug\nft

my mknft.exe is in : D:\Projects\Rust\mknft\target\debug\

I execute it like;

mknft.exe prepare D:\Projects\Rust\mknft\target\debug\examples\mknft.psd D:\Projects\Rust\mknft\target\debug\nft --name test

The error I get is;

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 183, kind: AlreadyExists, message: "Cannot create a file when that file already exists." }', src\commands\prepare.rs:45:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Surely I am doing something wrong when passing arguments.

How should the SRC , DEST parameters should appear?

**Comment by gregl83** [comment]
It's been a bit since I've worked through this project, it was used to deploy several NFT collections awhile back, but the questions over the last few days have me interested in doing some feature rounds starting with completion of the documentation.

The `mknft` command has two steps that result in separate builds.

First is the `prepare` command which produces the layer contents and a configuration file named `config.json`. The destination (`dest`) should be a directory name that doesn't already exist. If the directory already exists there *can* be a file name collision, for files `prepare` outputs, that would result in the error you observed. An important note is that the mknft example includes a `config.json` along with the PSD that indicates the probability, weight attribute, a certain trait will be used when generating the NFTs. You can save the output of `prepare` to rebuild the NFT collection using less space since only the configuration and layers are saved.

Second is the `package` command which is intended on building the final NFT set and `config.json` which *could* be used when deploying the NFTs to a contract. The output of this command will include every NFT that has been generated. This will use much more disk space. The same filename collisions can occur with the output of this command so it's best to just use a new directory for this step.

**Use a new destination directory for `prepare` and `package` and collisions will not occur.**

Then you also have different states of your NFTs persisted.

Thank you for interest in the project and my apologies for what was a quickly produce package! I'm inspired to invest some more time into it so more people can leverage the tool set with less unknowns and gotchas.

**Comment by gregl83** [comment]
I'm guessing this was either enough to build your NFTs or you've decided down another path, either way. I'm closing this particular issue for now.

For anyone else, using the `--help` or `-h` argument to mknft commands displays example usage.
